export const usersMock = [
  {
    username: "user1",
    email: "user1@example.com",
    name: "User One",
    password: "password1",
    rol: 1,
    createdAt: "2024-03-28T12:00:00Z",
    updatedAt: "2024-03-28T12:00:00Z",
  },
  {
    username: "user2",
    email: "user2@example.com",
    name: "User Two",
    password: "password2",
    rol: 1,
    createdAt: "2024-03-28T12:00:00Z",
    updatedAt: "2024-03-28T12:00:00Z",
  },
  {
    username: "user3",
    email: "user3@example.com",
    name: "User Three",
    password: "password3",
    rol: 1,
    createdAt: "2024-03-28T12:00:00Z",
    updatedAt: "2024-03-28T12:00:00Z",
  },
];

export const casosMock = [
  {
    id: 1,
    latitud: 10.12345,
    longitud: -75.54321,
    asignadoPor: "Asignado 1",
    nombreInspector: "Inspector 1",
    nroOgpeSbp: "123ABC",
    nroCatastro: "456XYZ",
    fechaRevision: "2024-03-25",
    estatus: "Pendiente",
    region: "Región 1",
    pueblo: "Pueblo 1",
    areaOperacional: "Área Operacional 1",
    fechaRecibido: "2024-03-24",
    createdAt: "2024-03-28T12:00:00Z",
    updatedAt: "2024-03-28T12:00:00Z",
    documento: {
      escrituras: "contenido_escrituras_1",
      evidenciaServicio: "contenido_evidencia_1",
      evidenciaTitularidad: "contenido_evidencia_titularidad_1",
      plano: "contenido_plano_1",
      planoInscripcion: "contenido_inscripcion_1",
      planoSituacion: "contenido_situacion_1",
      fotoPredioArea: "contenido_foto_predio_1",
      memorialSubsanacion: "contenido_memorial_1",
      memoExplicativo: "contenido_memo_explicativo_1",
      mapaEsquematico: "contenido_mapa_esquematico_1",
      credencialIngArq: "contenido_credencial_1",
      crtAut: "contenido_crt_1",
      AAA1190: "contenido_AAA1190_1",
      cartaRecomendacion: "contenido_carta_recomendacion_1",
      createdAt: "2024-03-28T12:00:00Z",
      updatedAt: "2024-03-28T12:00:00Z",
    },
  },
  {
    id: 2,
    latitud: 11.98765,
    longitud: -76.12345,
    asignadoPor: "Asignado 2",
    nombreInspector: "Inspector 2",
    nroOgpeSbp: "456DEF",
    nroCatastro: "789UVW",
    fechaRevision: "2024-03-26",
    estatus: "En proceso",
    region: "Región 2",
    pueblo: "Pueblo 2",
    areaOperacional: "Área Operacional 2",
    fechaRecibido: "2024-03-23",
    createdAt: "2024-03-28T12:00:00Z",
    updatedAt: "2024-03-28T12:00:00Z",
    documento: {
      escrituras: "contenido_escrituras_2",
      evidenciaServicio: "contenido_evidencia_2",
      evidenciaTitularidad: "contenido_evidencia_titularidad_2",
      plano: "contenido_plano_2",
      planoInscripcion: "contenido_inscripcion_2",
      planoSituacion: "contenido_situacion_2",
      fotoPredioArea: "contenido_foto_predio_2",
      memorialSubsanacion: "contenido_memorial_2",
      memoExplicativo: "contenido_memo_explicativo_2",
      mapaEsquematico: "contenido_mapa_esquematico_2",
      credencialIngArq: "contenido_credencial_2",
      crtAut: "contenido_crt_2",
      AAA1190: "contenido_AAA1190_2",
      cartaRecomendacion: "contenido_carta_recomendacion_2",
      createdAt: "2024-03-28T12:00:00Z",
      updatedAt: "2024-03-28T12:00:00Z",
    },
  },
  {
    id: 3,
    latitud: 12.34567,
    longitud: -77.23456,
    asignadoPor: "Asignado 3",
    nombreInspector: "Inspector 3",
    nroOgpeSbp: "789GHI",
    nroCatastro: "012JKL",
    fechaRevision: "2024-03-27",
    estatus: "Completado",
    region: "Región 3",
    pueblo: "Pueblo 3",
    areaOperacional: "Área Operacional 3",
    fechaRecibido: "2024-03-22",
    createdAt: "2024-03-28T12:00:00Z",
    updatedAt: "2024-03-28T12:00:00Z",
    documento: {
      escrituras: "contenido_escrituras_3",
      evidenciaServicio: "contenido_evidencia_3",
      evidenciaTitularidad: "contenido_evidencia_titularidad_3",
      plano: "contenido_plano_3",
      planoInscripcion: "contenido_inscripcion_3",
      planoSituacion: "contenido_situacion_3",
      fotoPredioArea: "contenido_foto_predio_3",
      memorialSubsanacion: "contenido_memorial_3",
      memoExplicativo: "contenido_memo_explicativo_3",
      mapaEsquematico: "contenido_mapa_esquematico_3",
      credencialIngArq: "contenido_credencial_3",
      crtAut: "contenido_crt_3",
      AAA1190: "contenido_AAA1190_3",
      cartaRecomendacion: "contenido_carta_recomendacion_3",
      createdAt: "2024-03-28T12:00:00Z",
      updatedAt: "2024-03-28T12:00:00Z",
    },
  },
];

export const options = [
  { value: "iniciado", label: "Iniciado" },
  { value: "verificacion", label: "Verificacion Inicial" },
  { value: "solicitaPlanos", label: "Se Solicita Planos" },
  { value: "reporteInicial", label: "Preparacion de reporte inicial" },
  { value: "asignado", label: "Asignado a investigaciòn" },
  { value: "referidoGTA", label: "Referido a GTA" },
  { value: "reporteCompletado", label: "Preparaciòn de reporte completado" },
  { value: "cartaRecomendacion", label: "Carta de recomendacion completada" },
  { value: "completado", label: "Listo para trasferir a PPP" },
];
